name: Sample
version: 1.0.0.0 # Optional

worker-dir:
    name: worker-Prime-Sample
    dir:
        - name: Prime-Sample
          source: git://github.com/ReedOei/Prime-Sample.git
          dir:
              - name: log.txt
              - name: test.zip
                source: server://file/test.zip
                script:
                    - unzip test.zip


