name:                Amphictyonis
version:             0.1.0.0
github:              "ReedOei/Amphictyonis"
license:             BSD3
author:              "Reed Oei"
maintainer:          "oei.reed@gmail.com"
copyright:           "2018 Reed Oei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ReedOei/Amphictyonis#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- split
- directory
- scotty
- postgresql-simple
- optparse-applicative
- text
- bytestring
- wreq
- hostname
- containers
- unordered-containers
- aeson
- lens-aeson

library:
  source-dirs: src

executables:
  amphi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Amphictyonis

tests:
  Amphictyonis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Amphictyonis
